dist: xenial
language: ruby
rvm:
  - ruby-head
  - 2.6
  - 2.5
  - 2.4
  - 2.3
before_install:
  - wget -O /tmp/julia.tar.gz https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.0-linux-x86_64.tar.gz
  - sudo mkdir /usr/local/julia
  - sudo tar xf /tmp/julia.tar.gz -C /usr/local/julia --strip-components=1
  - export PATH="/usr/local/julia/bin:$PATH"
